codecov:
  require_ci_to_pass: yes

comment:
  layout: "files"
  behavior: default
  require_changes: no

coverage:
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 90%
