line-length = 100
##extend-exclude = ["*.ipynb", "**/*_pb2.py"]

[lint]
ignore = [
    "PLR0913", # Too many arguments
    "S311", # suspicious-non-cryptographic-random-usage
    "G004" # Logging statement uses f-string
]
select = [
    "A",  # flake8-builtins
    "C4",  # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "B",
    "B9",
    "C",
    "G",  # flake8-logging-format
    "PYI",  # flake8-pyi
    "PT",  # flake8-pytest-style
    "TCH",  #  flake8-type-checking
    "C90",  # MCCabe
    "D",  # Pydocstyle
    "E",  # Pycodestyle error
    "F",  # Pyflakes
    "I",  # Isort
    "N",  # pep8-naming
    "W",  # Pycodestyle warning
#    "ANN",  # flake8-annotations
    "S",  # flake8-bandit
    "BLE",  # flake8-blind-except
    "PD",  # pandas-vet
    "PL",  # Pylint
    "RUF",  # Ruff
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/*" = ["ANN", "D", "S101", "PT", "PLR", "PD901"]
"integration_tests/*" = ["ANN", "D", "S101", "PT", "PLR", "PD901"]

[lint.pydocstyle]
convention = "google"

#[mccabe]
#max-complexity = 18
#
#
