name: Maschinenbau

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  sync-blueprints:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: "${{ secrets.MASCHINENBAU_APP_ID }}"
          private_key: "${{ secrets.MASCHINENBAU_APP_PRIVATE_KEY }}"
      - name: Maschinenbau
        uses: chr1st1ank/maschinenbau@main
        with:
          blueprints: >-
            github-paperwork
          github-token: ${{ secrets.GITHUB_TOKEN }}
          blueprint-vars: >-
            license=apache2
