name: Test workflow

permissions:
  checks: write
  pull-requests: write

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

    branches: [ master, main, release ]
  pull_request:
    branches: [ master, main, release ]

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.13"]
        exclude:
          # Reincluded with more parameters below
          - os: ubuntu-latest
            python-version: "3.9"
        include:
          - python-version: "3.9"
            os: ubuntu-latest
            publish-results: true
            tox-full-run: true
          - python-version: "3.10"
            os: ubuntu-latest
          - python-version: "3.11"
            os: ubuntu-latest
          - python-version: "3.12"
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: |
          uv tool install --with tox-gh-actions --with tox-uv tox

      - name: Test with tox
        if: ${{ !matrix.tox-full-run }}
        run:
          tox -e test

      - name: Test with tox
        if: ${{ matrix.tox-full-run }}
        run:
          tox

      - name: list files
        if: ${{ always() }}
        run: ls -l .

      - name: Publish Test Results
        if: ${{ matrix.publish-results && always() }}
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          junit_files: pytest.xml

      - uses: codecov/codecov-action@v4
        if: ${{ matrix.publish-results && always() }}
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml

  publish_dev_build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Build wheels and source tarball
        run: |
          uv build
      - name: publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
          verbose: true
